### ISSUE TITLE
Add particles to Notifications

### ISSUE THREAD

**Issue by chicoferreira** [chicoferreira/lifestealer#40]
```yaml
  consume heart success:
    action bar: "<white>+<amount><heart>"
    sound: minecraft:entity.player.levelup
    particle:
        type: "..."
        amount: ""
```
